name: Minecraft Java Bot No 1 by ks_warrior

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: ks-mc-bot
  cancel-in-progress: true

jobs:
  run-mc-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Create Bot File with Leading Spaces
        shell: bash
        run: |
          cat > ks-bot.js <<'EOF'
           // Install packages first:
           // npm install mineflayer mineflayer-pathfinder

           const mineflayer = require('mineflayer');
           const { pathfinder, Movements, goals } = require('mineflayer-pathfinder');

           const SERVER = 'aerio_smp.aternos.me';
           const PORT = 29538;
           const USERNAME = 'Player1';

           let bot;

           function createBot() {
            bot = mineflayer.createBot({
             host: SERVER,
             port: PORT,
             username: USERNAME,
            });

            bot.loadPlugin(pathfinder);

            bot.on('spawn', () => {
             console.log('Bot has spawned in the world!');
            });

            bot.on('chat', (username, message) => {
             if (username === bot.username) return;
             console.log(`<${username}> ${message}`);
             // Simple auto-reply
             if (message.toLowerCase().includes('hello')) {
              bot.chat(`Hello ${username}!`);
             }
            });

            bot.on('error', (err) => {
             console.log('Error:', err);
            });

            bot.on('end', () => {
             console.log('Bot disconnected, reconnecting in 5s...');
             setTimeout(createBot, 5000);
            });

            // Anti-AFK: random jump and walk
            setInterval(() => {
             if (!bot.entity) return;
             const random = Math.random();
             if (random < 0.5) bot.setControlState('jump', true);
             setTimeout(() => bot.setControlState('jump', false), 500);
             if (random >= 0.5) {
              const dx = (Math.random() - 0.5) * 2;
              const dz = (Math.random() - 0.5) * 2;
              bot.setControlState('forward', true);
              bot.setControlState('back', false);
              bot.setControlState('left', dx < 0);
              bot.setControlState('right', dx > 0);
              setTimeout(() => bot.setControlState('forward', false), 2000);
             }
            }, 10000); // every 10 seconds
           }

           createBot();
          EOF

      - name: Install dependencies
        shell: bash
        run: |
          npm init -y
          npm install mineflayer mineflayer-pathfinder

      - name: Start Minecraft Bot (300m runtime)
        shell: bash
        run: |
          timeout 85 node ks-bot.js || true

      - name: Restart Workflow (every 5h)
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ always() }}
        with:
          workflow: Minecraft Java Bot No 1 by ks_warrior
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
