name: Minecraft Java Bot No 1 by ks_warrior

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: ks-mc-bot
  cancel-in-progress: true

jobs:
  run-mc-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 2   # GitHub limit for public repos (6h)

    steps:
    # --- Checkout repository ---
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Setup Node.js ---
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    # --- Create Bot Script ---
    - name: Create Bot File
      run: |
        cat > ks-bot.js <<'EOF'
        const mineflayer = require('mineflayer')
        const { pathfinder, goals } = require('mineflayer-pathfinder')
        const { Authflow } = require('prismarine-auth')
        const fs = require('fs')
        const path = require('path')

        function createBot() {
          const cacheDir = path.join(__dirname, '.tokens')
          if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir)

          const authflow = new Authflow(process.env.MC_EMAIL, cacheDir)

          const bot = mineflayer.createBot({
            host: 'aerio_smp.aternos.me',
            port: 29538,
            auth: 'microsoft',
            version: '1.21.5',
            authflow: authflow
          })

          bot.loadPlugin(pathfinder)

          bot.on('spawn', () => {
            console.log(`${bot.username} has joined the server!`)
            bot.chat(`Hello, I am ${bot.username}, a bot by ks_warrior!`)

            // Anti-AFK
            setInterval(() => {
              const actions = [
                () => bot.setControlState('jump', true),
                () => bot.setControlState('jump', false),
                () => bot.setControlState('forward', true),
                () => bot.setControlState('forward', false),
                () => bot.look(Math.random() * 360, 0, true)
              ]
              actions[Math.floor(Math.random() * actions.length)]()
            }, 30000)
          })

          bot.on('chat', (username, message) => {
            if (username === bot.username) return

            if (message === '!jump') {
              bot.chat('Jumping!')
              bot.setControlState('jump', true)
              setTimeout(() => bot.setControlState('jump', false), 1000)
            }

            if (message.startsWith('!say ')) {
              bot.chat(message.slice(5))
            }

            if (message === '!come') {
              const player = bot.players[username]?.entity
              if (player) {
                bot.chat(`Coming to ${username}`)
                bot.pathfinder.setGoal(new goals.GoalNear(player.position.x, player.position.y, player.position.z, 1))
              } else {
                bot.chat("I can't see you.")
              }
            }
          })

          bot.on('death', () => {
            console.log('Bot died, waiting to respawn...')
          })

          bot.on('end', () => {
            console.log('Bot disconnected, reconnecting in 5s...')
            setTimeout(createBot, 5000)
          })
        }

        createBot()
        EOF

    # --- Install Dependencies ---
    - name: Install dependencies
      run: |
        npm init -y
        npm install mineflayer mineflayer-pathfinder prismarine-auth

    # --- Start Bot ---
    - name: Start Minecraft Bot
      env:
        MC_EMAIL: ${{ secrets.MC_EMAIL }}
      run: |
        node ks-bot.js

    # --- Restart Loop ---
    - name: Restart Workflow
      if: ${{ always() }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Minecraft Java Bot No 1 by ks_warrior
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
